### ISSUE TITLE
Bug: The getlist does not currently support sorting.

### ISSUE THREAD

**Issue by void-gfly** [thijsmie/pocketbase#10]
# Description
"sort": "-created" 
No matter how you specify it, it doesn't work, and looking through the source code, I don't see any program that handles the sort keyword.

ps. The same code works fine in the synchronised version

**Comment by void-gfly** [comment]
Adding the following code to the get_list function in crud.py solves the problem:

        if options and "sort" in options:
            send_options["params"]["sort"] = options["sort"]

**Comment by thijsmie** [comment]
Hi @void-gfly!

Good catch! Do you want to make the PR yourself as a first contribution or should I pick this up?

**Comment by thijsmie** [comment]
Your suggestion has been implemented!
