### ISSUE TITLE
Feature: Subclass `PocketbaseError` more to have more granular error catching capabilityes

### ISSUE THREAD

**Issue by Paillat-dev** [thijsmie/pocketbase#12]
# Rationale

Improving error handling in applications that interact with external services, like PocketBase, is crucial for robust and maintainable code. By subclassing `PocketbaseError` to create more specific error classes, such as `NotFound`, developers can write clearer, more explicit exception handling blocks. This approach allows for more granular control over error handling, making the code easier to understand and maintain. It also enhances the ability to catch and handle specific errors without cluttering the code with checks for specific error messages or codes, leading to cleaner and more Pythonic error handling practices.

# The How

To implement this improvement, you would subclass `PocketbaseError` to create more specific exceptions. For example, a `NotFound` exception could be raised when a 404 error is encountered. This requires modifying or extending the PocketBase client to catch generic `PocketbaseError` exceptions, inspect them for specific error codes or messages, and then raise the more specific exceptions as appropriate.

Here's an example of how you might define a `NotFound` exception and raise it:

```python
class NotFound(PocketbaseError):
    """Exception raised when a requested resource is not found."""
    pass

async def some_function(r):
    if r.status == 404:
        raise NotFound(e.data.get("message"))
    else:
        return r.json()

# Usage within an async function
try:
    # Attempt to retrieve a resource that might not exist
except NotFoundas e:
    print("Not found")
```

# The How Not

An alternative approach is to directly check the error code or message within each `except` block where `PocketbaseError` is caught. This method does not require subclassing `PocketbaseError`, but it leads to repetitive and cluttered error handling code, especially in larger applications where the same checks might be needed in multiple places.

Example of the less preferred method:

```python
try:
    # Some operation that might fail with a 404
except PocketbaseError as e:
    if e.data.get("code") == 404:
        print("Not found")
    else:
        raise e
```

This approach is less desirable because it mixes error handling logic with business logic, making the code harder to read and maintain.

# But There Is More

For further reading on Python's recommendations for exception handling and creating custom exceptions, the Python Enhancement Proposals (PEPs) provide valuable guidelines. Specifically, PEP 352 which discusses part of Python's error and exception handling conventions.

- PEP 352: https://peps.python.org/pep-0352/

**Comment by thijsmie** [comment]
Yes! This was always the plan, at least in my head. I'll see if I can pick this up soon, or are you interested in giving this a try yourself?

**Comment by Paillat-dev** [comment]
I might do it but I would have to learn more about the codebase so I can't promise that it will be quick. So if you want I can try to do it, but it will probably take some time.

**Comment by thijsmie** [comment]
I don't mind it taking time, so feel free to give it a go, and let me know if you need help or still rather let me do it.

**Comment by thijsmie** [comment]
I have picked this up seeing I had some time. Do you have time to give it a trialrun?

**Comment by Paillat-dev** [comment]
Yeah sure, i had other things to do and forgot this entirely, 😆
