### ISSUE TITLE
Bug: sort does nothing in get_list

### ISSUE THREAD

**Issue by Glinte** [thijsmie/pocketbase#14]
# Description

Using sort as part of the 

# Steps to reproduce

Make a table and do get_list where options is a `ListOptions` that includes a `sort` key. The exact code I ran is:
```python
res = await pb.collection("checkpoints_test").get_list(
        1, 1, {"filter": "thread_id='1'", "sort": "-thread_ts"}
    )
```

I debugged into
In CrudService.get_list
-> Service._send
-> Service._send_raw
-> Service._init_send
and saw that the sort key in options is completely ignored in the built Request url
![img_v3_02cv_f77a6b9c-0d2a-4100-af17-085d35f62fhu](https://github.com/user-attachments/assets/6ae789eb-2e80-4666-a85c-28aa69dd163d)

# Expected behavior

URL includes sort=-thread_ts

# [Optional] Stacktrace

```
Stacktrace
```

# Environment
 - Operating system: Linux/Windows
 - Python version: 3.11.8
 - Upstream PocketBase version: 
 - pocketbase-async version: 0.9.0

**Comment by thijsmie** [comment]
Hi @Glinte!

This was actually implemented, I just missed clicking the release button it seems! I've done that now and updating to 0.10.0 should fix your issue. Let me know if that works for you!

**Comment by Glinte** [comment]
Thanks, it is working as expected now. Not to be mad at you but I wish unimplemented methods are either non-existent in the published module or raises NotImplementedError because I spent quite a few hours going increasingly insane
