### ISSUE TITLE
Bug: Typo in hello_world.py

### ISSUE THREAD

**Issue by Pwea** [thijsmie/pocketbase#18]
There is a typo in the file [hello_world.py](https://github.com/thijsmie/pocketbase/blob/main/examples/hello_world.py).
At line 13 "admin" needs to be changed to "admins".
Great error system by the way! I got this nice and comprehensive message when I ran the code:
AttributeError: 'PocketBase' object has no attribute 'admin'. Did you mean: 'admins'?

# Environment
 - Operating system: Linux (Ubuntu)
 - Python version: 3.11
 - Upstream PocketBase version: 0.22.21
 - pocketbase-async version: 0.11.0

**Comment by thijsmie** [comment]
Fixed by @0xjimm in https://github.com/thijsmie/pocketbase/pull/17
